yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, null=True)
    description = models.TextField()

    def __str__(self) -> str:
        return f'{self.title}'


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='gr_posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        max_length=500,
        verbose_name='Текст',
        help_text='Текст нового комментария'
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Наблюдаемый'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Добавить изображение'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import get_paginator
from typing import Union
from django.http import HttpRequest, HttpResponse
from django.template.response import TemplateResponse


def index(request):
    posts = Post.objects.select_related('author', 'group')
    context = {'page_obj': get_paginator(posts, request)}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    context = {
        'group': group,
        'page_obj': get_paginator(posts, request)
    }
    return render(request, 'posts/group_list.html', context)


# использование select_related, рефакторинг функции group_posts

# def group_posts(request, slug):
#     group = get_object_or_404(Group, slug=slug)
#     posts = group.gr_posts.select_related('author', 'group')
#     context = {
#         'group': group,
#         'page_obj': get_paginator(posts, request)
#     }
#     return render(request, 'posts/group_list.html', context)


def profile(request, username, following=False):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('author')
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author=author,
            user=request.user
        ).exists()
    context = {
        'author': author,
        'following': following,
        'page_obj': get_paginator(post_list, request)
    }
    return render(request, 'posts/profile.html', context)


# использование полиформизма, рефакторинг функции profile

# def is_following(author, user):
#     return Follow.objects.filter(author=author, user=user).exists()

# def profile(request, username):
#     author = get_object_or_404(User, username=username)
#     post_list = author.posts.select_related('author')

#     following = False
#     if request.user.is_authenticated:
#         following = is_following(author, request.user)

#     context = {
#         'author': author,
#         'following': following,
#         'page_obj': get_paginator(post_list, request)
#     }
#     return render(request, 'posts/profile.html', context)


# реализация паттерна итератор для функции profile (строка 79-110)

# class PostIterator:
#     def __init__(self, user):
#         self.posts = user.posts.select_related('author')
#         self.index = 0

#     def __iter__(self):
#         return self

#     def __next__(self):
#         if self.index < len(self.posts):
#             post = self.posts[self.index]
#             self.index += 1
#             return post
#         else:
#             raise StopIteration


# @login_required
# def profile(request, username):
#     author = get_object_or_404(User, username=username)
#     post_iterator = PostIterator(author)  # Создаем итератор по постам автора
#     if request.user.is_authenticated:
#         following = Follow.objects.filter(
#             author=author,
#             user=request.user
#         ).exists()
#     context = {
#         'author': author,
#         'page_obj': post_iterator,
#         'following': following,
#     }
#     return render(request, 'posts/profile.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST,
        files=request.FILES or None,
    )
    if not request.method == 'POST' or not form.is_valid():
        return render(request,
                      'posts/create_post.html',
                      {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user)


# использование аннотирования функции,
# рефакторинг функции post_create

# @login_required
# def post_create(request: HttpRequest) -> Union[HttpResponse,
#                                                TemplateResponse]:
#     form = PostForm(
#         request.POST,
#         files=request.FILES or None,
#     )
#     if not request.method == 'POST' or not form.is_valid():
#         return render(request,
#                       'posts/create_post.html',
#                       {'form': form})
#     post = form.save(commit=False)
#     post.author = request.user
#     post.save()
#     return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    postedit = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=postedit
    )
    if postedit.author == request.user:
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html',
                  context={'form': form,
                           'is_edit': True,
                           'post_id': post_id})


# использование полиформизма, альтернативная функция post_edit

# def is_author(post, user):
#     return post.author == user


# @login_required
# def post_edit(request, post_id):
#     postedit = get_object_or_404(Post, pk=post_id)
#     form = PostForm(
#         request.POST or None,
#         files=request.FILES or None,
#         instance=postedit
#     )
#     if is_author(postedit, request.user) and form.is_valid():
#         form.save()
#         return redirect('posts:post_detail', post_id)
#     return render(request, 'posts/create_post.html',
#                   context={'form': form,
#                            'is_edit': True,
#                            'post_id': post_id})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

# без вызова оператора @, декорирование выглядело бы так
# add_comment = login_required(add_comment)


@login_required
def follow_index(request):
    post = (
        Post.objects
        .select_related('author')
        .filter(author__following__user=request.user)
    )
    page_obj = get_paginator(post, request)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if not Follow.objects.filter(
            user=request.user,
            author=author,
    ).exists() and author != request.user:
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    <title> Редактировать запись </title>
  {% else %}
    <title> Добавить запись </title>
  {% endif %}
{% endblock title %}
{% block content %}
{% load user_filters %}
<main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-body">
                  <form method="post"  enctype="multipart/form-data">
                    {% if is_edit %}
                      <h3>Редактировать запись</h3>
                    {% else %}
                      <h3>Добавить запись</h3>
                    {% endif %}
                    {% include 'posts/includes/forms.html' %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>          
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  {% block title %}
  <title> Мои подписки </title>
  {% endblock %}
  {% block content %} 
  {% include 'posts/includes/switcher.html' %}
    <div class="container py-5">      
      <h1>Последние обновления моих подписок</h1>
      {% for post in page_obj %}
          {% include 'posts/includes/post_list.html' %}
          {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  <title> Записи сообщества {{ group.title }} </title>
{% endblock title %}

{% block content %}
<h1> Записи сообщества {{ group.title }} </h1>
<h3> Всего постов: {{ group.gr_posts.count }} </h3>
  <p>{{ group.description|linebreaks }} </p>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.username }}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        <a href="{% url 'posts:post_detail' post.pk %}">пост</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
    {% if post.group %}   
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  <title> Последние обновления на сайте </title>
{% endblock title %}

{% load cache %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
{% cache 20 index_page with page_obj %}
{% if messages %}
              {% for message in messages %}
                <div class="alert alert-success" role="alert">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  <title> Пост {{ post.text|truncatechars:30 }} </title>
{% endblock title %}
{% block content %}
{% load user_filters %}
  <body> 
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:'d F Y' }}
            </li>
              {% if post.group %}
                <li class="list-group-item">
                  Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы 
                </a>
              {% endif %}
              </li>
              <li class="list-group-item">
                Автор: {{ post.author.username }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ post.author.posts.count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% if user.username == post.author.username %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
              редактировать запись
            </a>
          {% endif %}
        </article>

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}
      </div>
  </body>
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  <title> Профиль пользователя {{ author.username }} </title>
{% endblock title %}

{% block content %}
  <h1> Посты пользователя {{ author.username }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
  {% if request.user != author %}
  {% if following %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
    </a>
  {% endif %}
  {% endif %}
  <hr>
  {% for post in page_obj %}
    {% include 'posts/includes/post_list.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}